apiVersion: v1
kind: Service
metadata:
  name: blockchain-worker
  labels:
    app: blockchain-worker
spec:
  type: NodePort
  selector:
    app: blockchain-worker
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002
    nodePort: 50010